name: ML Pipeline CI

on:
  push:
    branches: [ develop, main ]
    paths: 
      - 'ml/**'
      - '.github/workflows/ci-ml.yml'
  pull_request:
    paths:
      - 'ml/**'
  schedule:
    - cron: '0 2 * * 0'  # Weekly retrain test

jobs:
  ml-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install ML dependencies
        run: |
          pip install -r ml/training/requirements.txt
          pip install pytest pytest-cov
          
      - name: Run ML unit tests
        run: |
          pytest tests/unit/test_ml* -v --cov=ml/
          
  training-test:
    runs-on: ubuntu-latest
    needs: ml-tests
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          
      - name: Install dependencies
        run: |
          pip install -r ml/training/requirements.txt
          
      - name: Run training test
        run: |
          cd ml/training
          python train.py --epochs 1 --samples 1000
          
      - name: Upload model artifact
        uses: actions/upload-artifact@v3
        with:
          name: trained-model
          path: ml/models/*.pkl
          
  model-validation:
    runs-on: ubuntu-latest
    needs: training-test
    steps:
      - uses: actions/checkout@v4
      
      - name: Download model artifact
        uses: actions/download-artifact@v3
        with:
          name: trained-model
          path: ml/models/
          
      - name: Validate model
        run: |
          python -c "
          import joblib
          import os
          model_files = [f for f in os.listdir('ml/models/') if f.endswith('.pkl')]
          if model_files:
              model = joblib.load(f'ml/models/{model_files[0]}')
              print(f'Model loaded successfully: {type(model)}')
          else:
              raise Exception('No model file found')
          "